name: EAS Preview App

on:
  pull_request:

permissions: write-all

jobs:
  preview:
    runs-on: ubuntu-latest
    environment: ENV
    env:
      EAS_OWNER: ${{ secrets.EAS_OWNER }}
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4

      - name: 🏗 Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: 🏗 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: pnpm

      - name: 🏗 Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 🚀 Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --branch ${{ github.event.pull_request.head.ref }}